import type {
  CachedApplicationGuide,
  CachedInterventionPlan,
  OfflineCache,
  OfflineEligibilityResult,
} from "./types";

function openPrint(html: string, title: string): void {
  if (typeof window === "undefined") return;
  const win = window.open("", "_blank", "noopener,noreferrer");
  if (!win) return;
  win.document.write(`<!doctype html><html><head><meta charset="utf-8" /><title>${title}</title>
  <style>
    body { font-family: ui-sans-serif, system-ui, sans-serif; color: #0f172a; padding: 32px; max-width: 880px; margin: 0 auto; }
    h1 { font-size: 22px; margin: 0 0 4px; }
    h2 { font-size: 16px; margin: 24px 0 8px; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; }
    h3 { font-size: 13px; margin: 12px 0 4px; }
    .muted { color: #64748b; font-size: 12px; }
    .badge { display: inline-block; padding: 2px 8px; border-radius: 999px; background: #f1f5f9; font-size: 11px; margin-right: 4px; }
    ul { padding-left: 18px; margin: 4px 0 8px; }
    .footer { margin-top: 32px; font-size: 11px; color: #64748b; border-top: 1px solid #e2e8f0; padding-top: 8px; }
    @media print { body { padding: 16px; } }
  </style>
  </head><body>${html}<div class="footer">Generated by Sarkari Sahayak — Offline CSC Assistance Engine. Source: locally synchronized welfare datasets.</div></body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 250);
}

function escape(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

export function exportEligibilitySummary(result: OfflineEligibilityResult): void {
  const rows = result.matches
    .map(
      (m) => `
      <div style="border:1px solid #e2e8f0;border-radius:8px;padding:12px;margin-bottom:8px;">
        <h3>${escape(m.schemeName)} <span class="badge">${escape(m.scope)}</span><span class="badge">${escape(m.category)}</span><span class="badge">Confidence: ${m.confidence}</span></h3>
        <ul>${m.matchedSignals.map((s) => `<li>${escape(s)}</li>`).join("")}</ul>
      </div>`,
    )
    .join("");
  const html = `
    <h1>Offline Eligibility Summary</h1>
    <div class="muted">Generated ${new Date(result.generatedAt).toLocaleString()} · Based on ${result.basedOnCachedSchemes} cached schemes</div>
    <h2>Citizen inputs</h2>
    <ul>
      <li>State: ${escape(result.input.state)}</li>
      <li>Occupation: ${escape(result.input.occupation)}</li>
      <li>Age: ${result.input.age}</li>
      <li>Annual income: ${escape(result.input.annual_income)}</li>
      <li>Disability status: ${result.input.disability_status ? "Yes" : "No"}</li>
    </ul>
    <h2>Matched schemes (${result.matches.length})</h2>
    ${rows || "<p class='muted'>No matches found in cached data.</p>"}
    <p class="muted"><strong>${escape(result.disclaimer)}</strong></p>
  `;
  openPrint(html, "Offline Eligibility Summary");
}

export function exportApplicationReport(guides: CachedApplicationGuide[]): void {
  const items = guides
    .slice(0, 50)
    .map(
      (g) => `
      <div style="border:1px solid #e2e8f0;border-radius:8px;padding:12px;margin-bottom:8px;">
        <h3>${escape(g.schemeName)}</h3>
        <div class="muted">Mode: ${escape(g.mode)} · Est. processing: ${escape(g.estimatedProcessingTime)}</div>
        <h3>Documents</h3>
        <ul>${g.documents.map((d) => `<li>${escape(d)}</li>`).join("") || "<li class='muted'>See official portal</li>"}</ul>
        <h3>Steps</h3>
        <ol>${g.steps.map((s) => `<li>${escape(s.title)}</li>`).join("")}</ol>
      </div>`,
    )
    .join("");
  const html = `
    <h1>Cached Application Guides</h1>
    <div class="muted">${guides.length} guides available offline</div>
    ${items}
  `;
  openPrint(html, "Cached Application Report");
}

export function exportInterventionSummary(
  cache: OfflineCache,
  interventions: CachedInterventionPlan[],
): void {
  const items = interventions
    .map(
      (i) => `
      <div style="border:1px solid #e2e8f0;border-radius:8px;padding:12px;margin-bottom:8px;">
        <h3>${escape(i.title)} <span class="badge">Priority: ${escape(i.priority)}</span><span class="badge">Impact: ${i.impactScore}</span></h3>
        <p>${escape(i.rationale)}</p>
        <p class="muted">${escape(i.expectedImpact)}</p>
      </div>`,
    )
    .join("");
  const html = `
    <h1>Offline Intervention Summary</h1>
    <div class="muted">Last sync: ${cache.lastSyncedAt ? new Date(cache.lastSyncedAt).toLocaleString() : "Never"}</div>
    ${items || "<p class='muted'>No cached interventions yet.</p>"}
  `;
  openPrint(html, "Offline Intervention Summary");
}
