/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelfareRoadmapRouteImport } from './routes/welfare-roadmap'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as ResearchObservatoryRouteImport } from './routes/research-observatory'
import { Route as PolicyIntelligenceRouteImport } from './routes/policy-intelligence'
import { Route as OutcomePredictionRouteImport } from './routes/outcome-prediction'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as KnowledgeGraphRouteImport } from './routes/knowledge-graph'
import { Route as InterventionPlannerRouteImport } from './routes/intervention-planner'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FamilyPlannerRouteImport } from './routes/family-planner'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as DigitalTwinRouteImport } from './routes/digital-twin'
import { Route as DecisionEngineRouteImport } from './routes/decision-engine'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommandCenterRouteImport } from './routes/command-center'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApplicationGuideRouteImport } from './routes/application-guide'
import { Route as AgentDashboardRouteImport } from './routes/agent-dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemesIdRouteImport } from './routes/schemes.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'

const WelfareRoadmapRoute = WelfareRoadmapRouteImport.update({
  id: '/welfare-roadmap',
  path: '/welfare-roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchObservatoryRoute = ResearchObservatoryRouteImport.update({
  id: '/research-observatory',
  path: '/research-observatory',
  getParentRoute: () => rootRouteImport,
} as any)
const PolicyIntelligenceRoute = PolicyIntelligenceRouteImport.update({
  id: '/policy-intelligence',
  path: '/policy-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const OutcomePredictionRoute = OutcomePredictionRouteImport.update({
  id: '/outcome-prediction',
  path: '/outcome-prediction',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeGraphRoute = KnowledgeGraphRouteImport.update({
  id: '/knowledge-graph',
  path: '/knowledge-graph',
  getParentRoute: () => rootRouteImport,
} as any)
const InterventionPlannerRoute = InterventionPlannerRouteImport.update({
  id: '/intervention-planner',
  path: '/intervention-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyPlannerRoute = FamilyPlannerRouteImport.update({
  id: '/family-planner',
  path: '/family-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DigitalTwinRoute = DigitalTwinRouteImport.update({
  id: '/digital-twin',
  path: '/digital-twin',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionEngineRoute = DecisionEngineRouteImport.update({
  id: '/decision-engine',
  path: '/decision-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandCenterRoute = CommandCenterRouteImport.update({
  id: '/command-center',
  path: '/command-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationGuideRoute = ApplicationGuideRouteImport.update({
  id: '/application-guide',
  path: '/application-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIdRoute = SchemesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchemesRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/assistant': typeof AssistantRoute
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/decision-engine': typeof DecisionEngineRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/eligibility': typeof EligibilityRoute
  '/family-planner': typeof FamilyPlannerRoute
  '/insights': typeof InsightsRoute
  '/intervention-planner': typeof InterventionPlannerRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/outcome-prediction': typeof OutcomePredictionRoute
  '/policy-intelligence': typeof PolicyIntelligenceRoute
  '/research-observatory': typeof ResearchObservatoryRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/welfare-roadmap': typeof WelfareRoadmapRoute
  '/profile/$id': typeof ProfileIdRoute
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/assistant': typeof AssistantRoute
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/decision-engine': typeof DecisionEngineRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/eligibility': typeof EligibilityRoute
  '/family-planner': typeof FamilyPlannerRoute
  '/insights': typeof InsightsRoute
  '/intervention-planner': typeof InterventionPlannerRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/outcome-prediction': typeof OutcomePredictionRoute
  '/policy-intelligence': typeof PolicyIntelligenceRoute
  '/research-observatory': typeof ResearchObservatoryRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/welfare-roadmap': typeof WelfareRoadmapRoute
  '/profile/$id': typeof ProfileIdRoute
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/assistant': typeof AssistantRoute
  '/command-center': typeof CommandCenterRoute
  '/dashboard': typeof DashboardRoute
  '/decision-engine': typeof DecisionEngineRoute
  '/digital-twin': typeof DigitalTwinRoute
  '/eligibility': typeof EligibilityRoute
  '/family-planner': typeof FamilyPlannerRoute
  '/insights': typeof InsightsRoute
  '/intervention-planner': typeof InterventionPlannerRoute
  '/knowledge-graph': typeof KnowledgeGraphRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/outcome-prediction': typeof OutcomePredictionRoute
  '/policy-intelligence': typeof PolicyIntelligenceRoute
  '/research-observatory': typeof ResearchObservatoryRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/welfare-roadmap': typeof WelfareRoadmapRoute
  '/profile/$id': typeof ProfileIdRoute
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-dashboard'
    | '/application-guide'
    | '/assistant'
    | '/command-center'
    | '/dashboard'
    | '/decision-engine'
    | '/digital-twin'
    | '/eligibility'
    | '/family-planner'
    | '/insights'
    | '/intervention-planner'
    | '/knowledge-graph'
    | '/navigator'
    | '/onboarding'
    | '/outcome-prediction'
    | '/policy-intelligence'
    | '/research-observatory'
    | '/schemes'
    | '/welfare-roadmap'
    | '/profile/$id'
    | '/schemes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-dashboard'
    | '/application-guide'
    | '/assistant'
    | '/command-center'
    | '/dashboard'
    | '/decision-engine'
    | '/digital-twin'
    | '/eligibility'
    | '/family-planner'
    | '/insights'
    | '/intervention-planner'
    | '/knowledge-graph'
    | '/navigator'
    | '/onboarding'
    | '/outcome-prediction'
    | '/policy-intelligence'
    | '/research-observatory'
    | '/schemes'
    | '/welfare-roadmap'
    | '/profile/$id'
    | '/schemes/$id'
  id:
    | '__root__'
    | '/'
    | '/agent-dashboard'
    | '/application-guide'
    | '/assistant'
    | '/command-center'
    | '/dashboard'
    | '/decision-engine'
    | '/digital-twin'
    | '/eligibility'
    | '/family-planner'
    | '/insights'
    | '/intervention-planner'
    | '/knowledge-graph'
    | '/navigator'
    | '/onboarding'
    | '/outcome-prediction'
    | '/policy-intelligence'
    | '/research-observatory'
    | '/schemes'
    | '/welfare-roadmap'
    | '/profile/$id'
    | '/schemes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  ApplicationGuideRoute: typeof ApplicationGuideRoute
  AssistantRoute: typeof AssistantRoute
  CommandCenterRoute: typeof CommandCenterRoute
  DashboardRoute: typeof DashboardRoute
  DecisionEngineRoute: typeof DecisionEngineRoute
  DigitalTwinRoute: typeof DigitalTwinRoute
  EligibilityRoute: typeof EligibilityRoute
  FamilyPlannerRoute: typeof FamilyPlannerRoute
  InsightsRoute: typeof InsightsRoute
  InterventionPlannerRoute: typeof InterventionPlannerRoute
  KnowledgeGraphRoute: typeof KnowledgeGraphRoute
  NavigatorRoute: typeof NavigatorRoute
  OnboardingRoute: typeof OnboardingRoute
  OutcomePredictionRoute: typeof OutcomePredictionRoute
  PolicyIntelligenceRoute: typeof PolicyIntelligenceRoute
  ResearchObservatoryRoute: typeof ResearchObservatoryRoute
  SchemesRoute: typeof SchemesRouteWithChildren
  WelfareRoadmapRoute: typeof WelfareRoadmapRoute
  ProfileIdRoute: typeof ProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welfare-roadmap': {
      id: '/welfare-roadmap'
      path: '/welfare-roadmap'
      fullPath: '/welfare-roadmap'
      preLoaderRoute: typeof WelfareRoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-observatory': {
      id: '/research-observatory'
      path: '/research-observatory'
      fullPath: '/research-observatory'
      preLoaderRoute: typeof ResearchObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policy-intelligence': {
      id: '/policy-intelligence'
      path: '/policy-intelligence'
      fullPath: '/policy-intelligence'
      preLoaderRoute: typeof PolicyIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outcome-prediction': {
      id: '/outcome-prediction'
      path: '/outcome-prediction'
      fullPath: '/outcome-prediction'
      preLoaderRoute: typeof OutcomePredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-graph': {
      id: '/knowledge-graph'
      path: '/knowledge-graph'
      fullPath: '/knowledge-graph'
      preLoaderRoute: typeof KnowledgeGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intervention-planner': {
      id: '/intervention-planner'
      path: '/intervention-planner'
      fullPath: '/intervention-planner'
      preLoaderRoute: typeof InterventionPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-planner': {
      id: '/family-planner'
      path: '/family-planner'
      fullPath: '/family-planner'
      preLoaderRoute: typeof FamilyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin': {
      id: '/digital-twin'
      path: '/digital-twin'
      fullPath: '/digital-twin'
      preLoaderRoute: typeof DigitalTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-engine': {
      id: '/decision-engine'
      path: '/decision-engine'
      fullPath: '/decision-engine'
      preLoaderRoute: typeof DecisionEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/command-center': {
      id: '/command-center'
      path: '/command-center'
      fullPath: '/command-center'
      preLoaderRoute: typeof CommandCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-guide': {
      id: '/application-guide'
      path: '/application-guide'
      fullPath: '/application-guide'
      preLoaderRoute: typeof ApplicationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard': {
      id: '/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$id': {
      id: '/schemes/$id'
      path: '/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof SchemesIdRouteImport
      parentRoute: typeof SchemesRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SchemesRouteChildren {
  SchemesIdRoute: typeof SchemesIdRoute
}

const SchemesRouteChildren: SchemesRouteChildren = {
  SchemesIdRoute: SchemesIdRoute,
}

const SchemesRouteWithChildren =
  SchemesRoute._addFileChildren(SchemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  ApplicationGuideRoute: ApplicationGuideRoute,
  AssistantRoute: AssistantRoute,
  CommandCenterRoute: CommandCenterRoute,
  DashboardRoute: DashboardRoute,
  DecisionEngineRoute: DecisionEngineRoute,
  DigitalTwinRoute: DigitalTwinRoute,
  EligibilityRoute: EligibilityRoute,
  FamilyPlannerRoute: FamilyPlannerRoute,
  InsightsRoute: InsightsRoute,
  InterventionPlannerRoute: InterventionPlannerRoute,
  KnowledgeGraphRoute: KnowledgeGraphRoute,
  NavigatorRoute: NavigatorRoute,
  OnboardingRoute: OnboardingRoute,
  OutcomePredictionRoute: OutcomePredictionRoute,
  PolicyIntelligenceRoute: PolicyIntelligenceRoute,
  ResearchObservatoryRoute: ResearchObservatoryRoute,
  SchemesRoute: SchemesRouteWithChildren,
  WelfareRoadmapRoute: WelfareRoadmapRoute,
  ProfileIdRoute: ProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
