/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NavigatorRouteImport } from './routes/navigator'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as FamilyPlannerRouteImport } from './routes/family-planner'
import { Route as EligibilityRouteImport } from './routes/eligibility'
import { Route as DecisionEngineRouteImport } from './routes/decision-engine'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ApplicationGuideRouteImport } from './routes/application-guide'
import { Route as AgentDashboardRouteImport } from './routes/agent-dashboard'
import { Route as DecisionEngineRouteImport } from './routes/decision-engine'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SchemesIdRouteImport } from './routes/schemes.$id'
import { Route as ProfileIdRouteImport } from './routes/profile.$id'

const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigatorRoute = NavigatorRouteImport.update({
  id: '/navigator',
  path: '/navigator',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyPlannerRoute = FamilyPlannerRouteImport.update({
  id: '/family-planner',
  path: '/family-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityRoute = EligibilityRouteImport.update({
  id: '/eligibility',
  path: '/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionEngineRoute = DecisionEngineRouteImport.update({
  id: '/decision-engine',
  path: '/decision-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationGuideRoute = ApplicationGuideRouteImport.update({
  id: '/application-guide',
  path: '/application-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardRoute = AgentDashboardRouteImport.update({
  id: '/agent-dashboard',
  path: '/agent-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionEngineRoute = DecisionEngineRouteImport.update({
  id: '/decision-engine',
  path: '/decision-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIdRoute = SchemesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SchemesRoute,
} as any)
const ProfileIdRoute = ProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/decision-engine': typeof DecisionEngineRoute
  '/eligibility': typeof EligibilityRoute
  '/family-planner': typeof FamilyPlannerRoute
  '/insights': typeof InsightsRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/profile/$id': typeof ProfileIdRoute
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/decision-engine': typeof DecisionEngineRoute
  '/eligibility': typeof EligibilityRoute
  '/family-planner': typeof FamilyPlannerRoute
  '/insights': typeof InsightsRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/profile/$id': typeof ProfileIdRoute
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-dashboard': typeof AgentDashboardRoute
  '/application-guide': typeof ApplicationGuideRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/decision-engine': typeof DecisionEngineRoute
  '/eligibility': typeof EligibilityRoute
  '/family-planner': typeof FamilyPlannerRoute
  '/insights': typeof InsightsRoute
  '/navigator': typeof NavigatorRoute
  '/onboarding': typeof OnboardingRoute
  '/schemes': typeof SchemesRouteWithChildren
  '/profile/$id': typeof ProfileIdRoute
  '/schemes/$id': typeof SchemesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-dashboard'
    | '/application-guide'
    | '/assistant'
    | '/dashboard'
    | '/decision-engine'
    | '/eligibility'
    | '/family-planner'
    | '/insights'
    | '/navigator'
    | '/onboarding'
    | '/schemes'
    | '/profile/$id'
    | '/schemes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-dashboard'
    | '/application-guide'
    | '/assistant'
    | '/dashboard'
    | '/decision-engine'
    | '/eligibility'
    | '/family-planner'
    | '/insights'
    | '/navigator'
    | '/onboarding'
    | '/schemes'
    | '/profile/$id'
    | '/schemes/$id'
  id:
    | '__root__'
    | '/'
    | '/agent-dashboard'
    | '/application-guide'
    | '/assistant'
    | '/dashboard'
    | '/decision-engine'
    | '/eligibility'
    | '/family-planner'
    | '/insights'
    | '/navigator'
    | '/onboarding'
    | '/schemes'
    | '/profile/$id'
    | '/schemes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentDashboardRoute: typeof AgentDashboardRoute
  ApplicationGuideRoute: typeof ApplicationGuideRoute
  AssistantRoute: typeof AssistantRoute
  DashboardRoute: typeof DashboardRoute
  DecisionEngineRoute: typeof DecisionEngineRoute
  EligibilityRoute: typeof EligibilityRoute
  FamilyPlannerRoute: typeof FamilyPlannerRoute
  InsightsRoute: typeof InsightsRoute
  NavigatorRoute: typeof NavigatorRoute
  OnboardingRoute: typeof OnboardingRoute
  SchemesRoute: typeof SchemesRouteWithChildren
  ProfileIdRoute: typeof ProfileIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigator': {
      id: '/navigator'
      path: '/navigator'
      fullPath: '/navigator'
      preLoaderRoute: typeof NavigatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-planner': {
      id: '/family-planner'
      path: '/family-planner'
      fullPath: '/family-planner'
      preLoaderRoute: typeof FamilyPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility': {
      id: '/eligibility'
      path: '/eligibility'
      fullPath: '/eligibility'
      preLoaderRoute: typeof EligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-engine': {
      id: '/decision-engine'
      path: '/decision-engine'
      fullPath: '/decision-engine'
      preLoaderRoute: typeof DecisionEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-guide': {
      id: '/application-guide'
      path: '/application-guide'
      fullPath: '/application-guide'
      preLoaderRoute: typeof ApplicationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard': {
      id: '/agent-dashboard'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard'
      preLoaderRoute: typeof AgentDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$id': {
      id: '/schemes/$id'
      path: '/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof SchemesIdRouteImport
      parentRoute: typeof SchemesRoute
    }
    '/profile/$id': {
      id: '/profile/$id'
      path: '/profile/$id'
      fullPath: '/profile/$id'
      preLoaderRoute: typeof ProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SchemesRouteChildren {
  SchemesIdRoute: typeof SchemesIdRoute
}

const SchemesRouteChildren: SchemesRouteChildren = {
  SchemesIdRoute: SchemesIdRoute,
}

const SchemesRouteWithChildren =
  SchemesRoute._addFileChildren(SchemesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentDashboardRoute: AgentDashboardRoute,
  ApplicationGuideRoute: ApplicationGuideRoute,
  AssistantRoute: AssistantRoute,
  DashboardRoute: DashboardRoute,
  DecisionEngineRoute: DecisionEngineRoute,
  EligibilityRoute: EligibilityRoute,
  FamilyPlannerRoute: FamilyPlannerRoute,
  InsightsRoute: InsightsRoute,
  NavigatorRoute: NavigatorRoute,
  OnboardingRoute: OnboardingRoute,
  SchemesRoute: SchemesRouteWithChildren,
  ProfileIdRoute: ProfileIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
